module.exports = {
  content: ['./src/**/*.svelte', 'safelist.txt'],
  theme: {
    extend: {},
  },
  plugins: [
    require('daisyui')
  ],
  daisyui: {
    themes: [
      {
        'dark': {
          'primary': '#0088CC',
          'primary-focus': '#0476ae',
          'primary-content': '#ffffff',
          'secondary': '#2BA9B1',
          'secondary-focus': '#23929a',
          'secondary-content': '#ffffff',
          'accent': '#714CA8',
          'accent-focus': '#5e3d8f',
          'accent-content': '#ffffff',
          'neutral': '#121D2B',
          'neutral-focus': '#0C131D',
          'neutral-content': '#ffffff',
          'base-100': '#1E3048',
          'base-200': '#18273A',
          'base-300': '#121D2B',
          'base-content': '#7EA3C8',
          'info': '#0179FB',
          'success': '#24A542',
          'warning': '#FFC007',
          'error': '#DC3444',
          '--rounded-box': '.5rem',
          '--rounded-btn': '.2rem',
          '--rounded-badge': '.2rem',
          '--animation-btn': '.1s',
          '--animation-input': '.1s',
          '--padding-card:': '.5rem',
        },
        'light': {
          'primary': '#0088CC',
          'primary-focus': '#0476ae',
          'primary-content': '#ffffff',
          'secondary': '#2BA9B1',
          'secondary-focus': '#23929a',
          'secondary-content': '#ffffff',
          'accent': '#714CA8',
          'accent-focus': '#5e3d8f',
          'accent-content': '#ffffff',
          'neutral': '#121D2B',
          'neutral-focus': '#0C131D',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#f9fafb',
          'base-300': '#d1d5db',
          'base-content': '#344055',
          'info': '#0179FB',
          'success': '#24A542',
          'warning': '#FFC007',
          'error': '#DC3444',
          '--rounded-box': '.5rem',
          '--rounded-btn': '.2rem',
          '--rounded-badge': '.2rem',
          '--animation-btn': '.1s',
          '--animation-input': '.1s',
          '--padding-card:': '.5rem',
        },
      },
    ],
  },
}
